### ISSUE TITLE
Error building on macOS Catalina

### ISSUE THREAD

**Issue by esimov** [dskart/rustcraft#3]
I'm trying to build on macOS Catalina, but getting the following error:

`XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.fonts was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.fonts was invalidated.}
rustcraft[70247:3351893] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
`

**Comment by dskart** [comment]
Hey! I am sorry this is happening to you. From what I can read, this doesn't look like it is an error with this repository but more to do something with your dev environment. I tried googling the error but didn't come up with anything related to rust or wgpu. 

Sorry I cannot be more helpful with this. If you do ever find out the error is related to this repos, don't hesitate to let me know!

I am closing this for now.
